/*
 *  UVCCamera
 *  library and sample to access to UVC web camera on non-rooted Android device
 *
 * Copyright (c) 2014-2017 saki t_saki@serenegiant.com
 * Copyright (c) 2024 vschryabest@gmail.com
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *
 *  All files in the folder are under this Apache License, Version 2.0.
 *  Files in the libjpeg-turbo, libusb, libuvc, rapidjson folder
 *  may have a different license, see the respective files.
 */
package com.jiangdg.usb

import android.util.SparseArray

object USBVendorId {
    val IDS = mapOf (
        10006 to "YUEN DA ELECTRONIC PRODUCTS FACTORY" ,
        10013 to "Gionee Communication Equipment Co. to Ltd. ShenZhen" ,
        10022 to "Universal Electronics Inc. (dba: TVIEW ," ,
        1003 to "Atmel Corporation" ,
        1006 to "Mitsumi" ,
        1008 to "HP Inc." ,
        10112 to "M31 Technology Corp." ,
        10113 to "Liteconn Co. to Ltd." ,
        10121 to "Suzhou WEIJU Electronics Technology Co. to Ltd." ,
        10144 to "Mondokey Limited" ,
        10149 to "Advantest Corporation" ,
        10150 to "iRobot Corporation" ,
        1020 to "Elitegroup Computer Systems" ,
        1021 to "Xilinx Inc." ,
        10226 to "Sibridge Tech." ,
        1026 to "ALi Corporation" ,
        1027 to "Future Technology Devices International Limited" ,
        10275 to "Dongguan Jiumutong Industry Co. to Ltd." ,
        10289 to "Power Integrations" ,
        10291 to "Oculus VR to Inc." ,
        10300 to "HIGH TEK HARNESS ENTERPRISE CO. to LTD." ,
        10316 to "Full in Hope Co. to Ltd." ,
        1032 to "Quanta Computer Inc." ,
        10329 to "Viconn Technology (HK , Co. to Ltd." ,
        1033 to "NEC Corporation" ,
        1035 to "Weltrend Semiconductor" ,
        1037 to "VIA Technologies to Inc." ,
        10374 to "Seeed Technology Co. to Ltd." ,
        10375 to "Specwerkz" ,
        1038 to "MCCI Corporation" ,
        10398 to "Esselte Leitz GmbH & Co. KG" ,
        10406 to "E-SEEK Inc." ,
        1041 to "BUFFALO INC." ,
        10423 to "Pleora Technologies Inc." ,
        10431 to "Vitetech Int'l Co. to Ltd." ,
        1044 to "Giga-Byte Technology Co. to Ltd." ,
        10446 to "Changzhou Shi Wujin Miqi East Electronic Co. to Ltd." ,
        10457 to "Shenzhen Ourconn Technology Co. to Ltd." ,
        10458 to "G.SKILL Int'l Enterprice Co. to Ltd." ,
        1046 to "Nuvoton Technology Corp." ,
        10466 to "Surplus Electronic Technology Co. to Ltd." ,
        10470 to "BIAMP SYSTEMS" ,
        10509 to "IBCONN Technologies (Shenzhen , Co. to Ltd." ,
        10510 to "Fugoo Inc." ,
        10519 to "Pan Xin Precision Electronics Co. to Ltd." ,
        10530 to "Dongguan Digi-in Digital Technology Co. to Ltd." ,
        1054 to "Creative Labs" ,
        10540 to "GENUSION to Inc." ,
        10544 to "Ineda Systems Inc." ,
        10545 to "Jolla Ltd." ,
        10546 to "Peraso Technologies to Inc." ,
        10549 to "Nanjing Magewell Electronics Co. to Ltd." ,
        10560 to "Shenzhen Yiwanda Electronics Co. to Ltd." ,
        1057 to "Nokia Corporation" ,
        10575 to "Dollar Connection Ltd." ,
        10595 to "BIO-key International to Inc." ,
        1060 to "Microchip-SMSC" ,
        10603 to "Xacti Corporation" ,
        10615 to "Shenzhen Zowee Technology Co. to Ltd." ,
        10643 to "ADPlaus Technology Limited" ,
        10646 to "Unwired Technology" ,
        1065 to "Cirrus Logic Inc." ,
        10657 to "Union Electric Plug & Connector Corp." ,
        10674 to "Canova Tech" ,
        10685 to "Silicon Works" ,
        10695 to "HANRICO ANFU ELECTRONICS CO. to LTD." ,
        10700 to "Kodak Alaris" ,
        10702 to "JGR Optics Inc." ,
        10703 to "Richtek Technology Corporation" ,
        10705 to "Binatone Electronics Int. Ltd." ,
        1071 to "Molex Inc." ,
        10715 to "Shenzhen iBoard Technology Co. to Ltd." ,
        10719 to "SMIT(HK , Limited" ,
        1072 to "Fujitsu Component Limited" ,
        10725 to "Dongguan Kechenda Electronic Technology Co. to Ltd." ,
        10726 to "Fengshun Peiying Electro-Acoustic Co. to Ltd." ,
        10744 to "MD ELEKTRONIK GmbH" ,
        10749 to "Bad Elf to LLC" ,
        10770 to "Vreo Limited" ,
        10772 to "Kanex" ,
        10781 to "Oxford Nanopore Technologies" ,
        10782 to "Obsidian Technology" ,
        10783 to "Lucent Trans Electronics Co. to Ltd." ,
        10784 to "GUOGUANG GROUP CO. to LTD." ,
        10788 to "CNPLUS" ,
        10789 to "Fourstar Group" ,
        10790 to "Tragant International Co. to Ltd." ,
        10791 to "DongGuan LianGang Optoelectronic Technology Co. to Ltd." ,
        10797 to "Atrust Computer Corp." ,
        10798 to "VIA Alliance Semiconductor Co. to Ltd." ,
        10799 to "BSUN Electronics Co. to Ltd." ,
        1080 to "Advanced Micro Devices" ,
        10807 to "RTD Embedded Technologies to Inc." ,
        10816 to "Shenzhen Choseal Industrial Co. to Ltd." ,
        10817 to "Canyon Semiconductor" ,
        10818 to "Spectra7 Microsystems Corp." ,
        10821 to "Meizu Technology Co. to Ltd." ,
        10822 to "Hubei Yingtong Telecommunication Cable Inc." ,
        10829 to "Wilder Technologies" ,
        10837 to "Diodes Inc." ,
        10846 to "DuPont" ,
        1085 to "Lexmark International Inc." ,
        10852 to "Zhejiang Songcheng Electronics Co. to Ltd." ,
        10859 to "VSN Mobil" ,
        10875 to "Bellwether Electronic Corp." ,
        10878 to "VAIO Corporation" ,
        10879 to "Perixx Computer GmbH" ,
        10885 to "HANK ELECTRONICS CO. to LTD" ,
        10892 to "Sonnet Technologies to Inc." ,
        10893 to "Keysight Technologies Inc." ,
        10895 to "Manutronics Vietnam Joint Stock Company" ,
        10900 to "G2 Touch Co. to Ltd." ,
        10902 to "Micromax Informatics Ltd" ,
        10910 to "SEIKO SOLUTIONS Inc." ,
        10912 to "Casco Products Corp." ,
        10922 to "Virtium Technology to Inc." ,
        10923 to "Field and Company LLC to dba Leef USA" ,
        10928 to "GM Global Technology Operations LLC" ,
        10931 to "Key Asic Inc." ,
        10943 to "Revolabs to Inc." ,
        10945 to "Lattice Semiconductor Corp" ,
        10947 to "Foshan Nanhai Saga Audio Equipment Co. to Ltd." ,
        10957 to "Silergy Corp." ,
        10963 to "Shenzhen Hali-Power Industrial Co. to Ltd." ,
        10971 to "I-PEX (Dai-ichi Seiko ," ,
        10973 to "SEE-PLUS INDUSTRIAL LTD." ,
        10990 to "Adapt-IP Company" ,
        10997 to "Libratone A/S" ,
        10999 to "Shenzhen Hazens Automotive Electronics (SZ , Co. to Ltd." ,
        11000 to "Jiangsu Toppower Automotive Electronics Co. to Ltd." ,
        11001 to "Drapho Electronics Technology Co. to Ltd." ,
        1102 to "Alps Electric Co. to Ltd." ,
        11022 to "Le Shi Zhi Xin Electronic Technology (Tian Jin , Limited" ,
        11024 to "Cardiac Insight to Inc." ,
        11028 to "EverPro Technologies Company to Ltd." ,
        11029 to "Rosenberger Hochfrequenztechnik" ,
        11035 to "Dongguan City Sanji Electronics Co. to Ltd." ,
        11037 to "Lintes Technology Co. to Ltd." ,
        11039 to "KinnexA to Inc." ,
        11042 to "Metra Electronics Corp." ,
        11044 to "KeepKey to LLC" ,
        11047 to "FluxData Incorporated" ,
        1105 to "Texas Instruments" ,
        11061 to "Assem Technology Co. to Ltd." ,
        11062 to "Dongguan City Jianghan Electronics Co. to Ltd." ,
        11063 to "Huizhou Desay SV Automotive Co. to Ltd." ,
        11064 to "Ningbo Rixing Electronics Co. to Ltd." ,
        11069 to "GuangDong YuanFeng Automotive Electroics Co. to Ltd." ,
        11080 to "Sounding Audio Industrial Limited" ,
        11082 to "Yueqing Huaxin Electronic Co. to Ltd." ,
        11098 to "Universal Audio to Inc." ,
        11111 to "Lifesize to Inc." ,
        11123 to "Pioneer DJ Corporation" ,
        11124 to "Embedded Intelligence to Inc." ,
        11125 to "New Matter" ,
        11126 to "Shanghai Wingtech Electronic Technology Co. to Ltd." ,
        11127 to "Epiphan Systems Inc." ,
        11130 to "Spin Master Far East Ltd." ,
        11131 to "Gigaset Digital Technology (Shenzhen , Co. to Ltd." ,
        11132 to "Noveltek Semiconductor Corp." ,
        11139 to "Silicon Line GmbH" ,
        11140 to "Ever Win International Corp." ,
        11144 to "Socionext Inc." ,
        11145 to "Ugreen Group Limited" ,
        11146 to "Shanghai Pateo Electronic Equipment Mfg. Co. to Ltd." ,
        1115 to "Renesas Electronics Corp." ,
        11154 to "i-BLADES to Inc." ,
        11155 to "Altia Systems Inc." ,
        11156 to "ShenZhen Baoyuanda Electronics Co. to Ltd." ,
        11157 to "iST - Integrated Service Technology Inc." ,
        11158 to "HYUNDAI MOBIS Co. to Ltd." ,
        11161 to "360fly to Inc." ,
        11162 to "HUIZHOU CHENG SHUO HARDWARE PLASTIC CO. to LTD." ,
        11163 to "Zhongshan Aute Electronics Technology Co. to Ltd." ,
        11164 to "Guangdong King Link Industrial Co. to Ltd." ,
        11167 to "Scietera Technologies to Inc." ,
        11168 to "InVue Security Products" ,
        11169 to "I-Sheng Electric Wire & Cable Co. to Ltd." ,
        11170 to "China Daheng Group Inc Beijing Image Vision Tech Branch" ,
        11171 to "Shenzhen FeiTianXia Technology Ltd." ,
        11172 to "Shenzhen HengJia New Energy Auto Part Co. to Ltd." ,
        11175 to "77 Elektronika Kft." ,
        11176 to "YUDU EASON ELECTRONIC CO. to LTD." ,
        1118 to "Microsoft Corporation" ,
        11181 to "XIN JI (SHENZHEN , COMPUTER PARTS CO. to LTD." ,
        11189 to "Silk ID Systems" ,
        11190 to "3D Imaging & Simulations Corp. (3DISC ," ,
        11191 to "Dongguan ChengXiang Industrial Co. to Ltd." ,
        11192 to "OCC (Zhuhai , Electronic Co. to Ltd." ,
        11194 to "Sinseader Electronic Co. to Ltd." ,
        11195 to "DONGGUAN YELLOWKNIFE Industrial Co. to Ltd." ,
        11197 to "RF Creations Ltd." ,
        11198 to "Chengyi Semiconductors (Shanghai , Co. to Ltd." ,
        11199 to "Shenzhen Shinning Electronic Co. to Ltd." ,
        11200 to "Shenzhen WFD Electronics Co. to Ltd." ,
        11201 to "Dongguan Sino Syncs Industrial Co. to Ltd." ,
        11202 to "JNTC Co. to Ltd." ,
        11208 to "DONGGUAN POLIXIN ELECTRIC CO. to LTD." ,
        11209 to "Tama Electric (Suzhou , Co. to Ltd." ,
        1121 to "Primax Electronics" ,
        11210 to "Exvision to Inc." ,
        11216 to "mophie to LLC" ,
        11219 to "Dongguan ULT-unite electronic technology co. to LTD" ,
        11220 to "JL Audio to Inc." ,
        11221 to "Cable Matters Inc." ,
        11222 to "CoroWare to Inc." ,
        11229 to "Charm Sciences Inc." ,
        1123 to "EATON" ,
        11230 to "Pickering Interfaces Limited" ,
        11231 to "Hangzhou Hikvision Digital Technology Co. to Ltd." ,
        11232 to "FULLINK ELECTRONICS TECHNOLOGY (SZ , LTD" ,
        11233 to "AutoChips Inc." ,
        11234 to "Electric Connector Technology Co. to Ltd." ,
        11237 to "LELTEK" ,
        11238 to "Dongguan KaiWin Electronics Co. to Ltd." ,
        11239 to "BEFS Co. to Ltd." ,
        11240 to "Archisite to Inc." ,
        11241 to "Magneti Marelli S.p.A Electr BL" ,
        11246 to "Ventev Mobile" ,
        11247 to "Quanta Storage Inc." ,
        11248 to "Tech-Top Technology Limited" ,
        11253 to "Shenzhen YOOBAO Technology Co. to Ltd." ,
        11254 to "Shenzhen Sinotek Technology Co. to Ltd." ,
        11255 to "KEYW" ,
        11256 to "Visual Land Inc." ,
        11264 to "MEEM SL Ltd" ,
        11265 to "Dongguan Arin Electronics Technology Co. to Ltd." ,
        11266 to "DongGuan City JianNuo Electronics Co. to Ltd." ,
        11268 to "Shenzhen XOX Electronics Co. to Ltd." ,
        11269 to "Protop International Inc." ,
        11270 to "Microsemi Semiconductor (US , Inc." ,
        11271 to "Webcloak LLC" ,
        11272 to "INVECAS INC." ,
        11274 to "ATANS Technology Inc." ,
        11275 to "Triple Win Precision Technology Co. to Ltd." ,
        11276 to "IC Realtech" ,
        11277 to "Embrava Pty Ltd" ,
        1128 to "Wieson Technologies Co. to Ltd." ,
        11280 to "Sinotronics Co. to Ltd." ,
        11281 to "ALLBEST ELECTRONICS TECHNOLOGY CO. to LTD." ,
        11282 to "Shenzhen Xin Kai Feng Electronics Factory" ,
        11283 to "MOST WELL Technology Corp." ,
        11284 to "Buffalo Memory Co. to Ltd." ,
        11285 to "Xentris Wireless" ,
        11286 to "Priferential Accessories Ltd" ,
        11289 to "Sunlike Technology Co. to Ltd." ,
        11290 to "Young Fast Optoelectronics Co. to Ltd." ,
        11291 to "ISAW Camera Inc" ,
        11298 to "Qanba USA to LLC" ,
        11299 to "Super Micro Computer Inc." ,
        11302 to "Micromax International Corporation" ,
        11304 to "Granite River Labs Japan Ltd." ,
        11305 to "Coagent Enterprise Limited" ,
        11306 to "LEIA Inc." ,
        11309 to "Shenzhen Ebull Technology Limited" ,
        1131 to "American Megatrends" ,
        11310 to "Hualun Technology Co. to Ltd." ,
        11311 to "Sensel to Inc." ,
        11319 to "Shenzhen Adition Audio Science & Technology Co. to Ltd." ,
        11320 to "Goldenconn Electronics Technology (Suzhou , Co. to Ltd." ,
        11321 to "JIB Electronics Technology Co. to Ltd." ,
        11322 to "Changzhou Shinco Automotive Electronics Co. to Ltd." ,
        11323 to "Shenzhen Hangsheng Electronics Corp. to Ltd." ,
        11324 to "Beartooth Radio to Inc." ,
        11325 to "Audience to A Knowles Company" ,
        11327 to "Nextbit Systems to Inc." ,
        11328 to "Leadtrend" ,
        11329 to "Adaptertek Technology Co. to Ltd." ,
        1133 to "Logitech Inc." ,
        11330 to "Feature Integration Technology Inc." ,
        11331 to "Avegant Corporation" ,
        11335 to "Chunghsin International Electronics Co. to Ltd." ,
        11336 to "Delphi Electrical Centers (Shanghai , Co. to Ltd." ,
        11341 to "VVETEK DOO" ,
        11347 to "Huizhou Foryou General Electronics Co. to Ltd." ,
        11348 to "LifeWatch Technologies Ltd." ,
        11349 to "Magicleap" ,
        11355 to "Dongguan City Shenglan Electronics Co. to LTD." ,
        11356 to "Neusoft Corporation" ,
        11357 to "SIP Simya Electronics Technology Co. to Ltd." ,
        11358 to "GNSD Automotive Co. to Ltd." ,
        11359 to "YOODS Co. to Ltd." ,
        11360 to "Sirin Mobile Technologies AG" ,
        11361 to "Jadmam Corporation dba: Boytone" ,
        11373 to "Gibson Innovations" ,
        11374 to "Shen Zhen Xian Shuo Technology Co. LTD" ,
        11375 to "PST Eletronica LTDA" ,
        11376 to "PERI to Inc." ,
        11377 to "Bozhou BoTong Information Technology Co. to Ltd." ,
        11383 to "Profindustry GmbH" ,
        11384 to "BRAGI GmbH" ,
        11385 to "WAWGD to Inc. (DBA: Foresight Sports ," ,
        11390 to "Dongguan Allpass Electronic Co. to Ltd." ,
        11391 to "SHENZHEN D-VITEC INDUSTRIAL CO. to LTD." ,
        11392 to "motomobile AG" ,
        11393 to "Indie Semiconductor" ,
        11397 to "Audientes" ,
        11403 to "Huizhou Dehong Technology Co. to Ltd." ,
        11404 to "PowerCenter Technology Limited" ,
        11405 to "Mizco International to Inc." ,
        11408 to "I. AM. PLUS to LLC" ,
        11409 to "Corigine to Inc." ,
        11410 to "Ningbo Yinzhou Shengke Electronics Co. to Ltd." ,
        11417 to "Prusa Research s.r.o." ,
        11423 to "e-Smart Systems Pvt. Ltd." ,
        11424 to "Leagtech Jiangxi Electronic Co. to Ltd." ,
        11425 to "Dongguan Yujia Electronics Technology Co. to Ltd." ,
        11426 to "GuangZhou MingPing Electronics Technology" ,
        11427 to "DJI Technology Co. to Ltd." ,
        11428 to "Shenzhen Alex Technology Co. to Ltd." ,
        11433 to "JITS TECHNOLOGY CO. to LIMITED" ,
        11434 to "LIVV Brand llc" ,
        11444 to "Ava Enterprises to Inc. dba: Boss Audio Systems" ,
        11448 to "Shenzhen Sydixon Electronic Technology Co. to Ltd." ,
        11449 to "On-Bright Electronics (Shanghai , Co. to Ltd." ,
        11450 to "Dongguan Puxu Industrial Co. to Ltd." ,
        11451 to "Shenzhen Soling Indusrtial Co. to Ltd." ,
        11453 to "EGGCYTE to INC." ,
        11455 to "Donggguan Yuhua Electronic Co. to Ltd." ,
        11456 to "Hangzhou Zero Zero Technology Co. to Ltd." ,
        11462 to "Prodigy Technovations Pvt Ltd" ,
        11463 to "EmergiTech to Inc" ,
        11464 to "Hewlett Packard Enterprise" ,
        11465 to "Monolithic Power Systems Inc." ,
        11467 to "USB Memory Direct" ,
        11468 to "Silicon Mitus Inc." ,
        11472 to "Technics Global Electronics & JCE Co. to Ltd." ,
        11478 to "Immersive Media" ,
        11479 to "Cosemi Technologies Inc." ,
        11481 to "Cambrionix Ltd" ,
        11482 to "CXUN Co. Ltd." ,
        11483 to "China Tsp Inc" ,
        11490 to "Yanfeng Visteon (Chongqing , Automotive Electronics Co" ,
        11491 to "Alcorlink Corp." ,
        11492 to "ISBC Ltd." ,
        11493 to "InX8 Inc dba: AKiTiO" ,
        11494 to "SDAN Tecchnology Co. to Ltd." ,
        11495 to "Lemobile Information Technology (Beijing , Co. to Ltd." ,
        11496 to "GongGuan HWX Electronic Technology Co. to Ltd." ,
        11497 to "Suzhu Jingshi Electronic Technology Co. to Ltd." ,
        11498 to "Zhong Shan City Richsound Electronic Industrial Ltd." ,
        11499 to "Dongguang Kangbang Electronics Co. to Ltd." ,
        1151 to "Plantronics to Inc." ,
        1154 to "Kyocera Corporation" ,
        1155 to "STMicroelectronics" ,
        1161 to "Foxconn / Hon Hai" ,
        1165 to "ITE Tech Inc." ,
        1177 to "Yamaha Corporation" ,
        1188 to "Hitachi to Ltd." ,
        1191 to "Visioneer" ,
        1193 to "Canon Inc." ,
        1200 to "Nikon Corporation" ,
        1201 to "Pan International" ,
        1204 to "Cypress Semiconductor" ,
        1205 to "ROHM Co. to Ltd." ,
        1207 to "Compal Electronics to Inc." ,
        1208 to "Seiko Epson Corp." ,
        1211 to "I-O Data Device to Inc." ,
        1221 to "Fujitsu Ltd." ,
        1227 to "FUJIFILM Corporation" ,
        1238 to "Mentor Graphics" ,
        1240 to "Microchip Technology Inc." ,
        1241 to "Holtek Semiconductor to Inc." ,
        1242 to "Panasonic Corporation" ,
        1245 to "Sharp Corporation" ,
        1250 to "Exar Corporation" ,
        1254 to "Identiv to Inc." ,
        1256 to "Samsung Electronics Co. to Ltd." ,
        1260 to "Tokyo Electron Device Limited" ,
        1266 to "Chicony Electronics Co. to Ltd." ,
        1271 to "Newnex Technology Corp." ,
        1273 to "Brother Industries to Ltd." ,
        1276 to "SUNPLUS TECHNOLOGY CO. to LTD." ,
        1278 to "PFU Limited" ,
        1281 to "Fujikura/DDK" ,
        1282 to "Acer to Inc." ,
        1287 to "Hosiden Corporation" ,
        1293 to "Belkin International to Inc." ,
        1300 to "FCI Electronics" ,
        1302 to "Longwell Electronics/Longwell Company" ,
        1305 to "Star Micronics Co. to LTD" ,
        13081 to "Mevo Inc" ,
        1309 to "American Power Conversion" ,
        1314 to "ACON to Advanced-Connectek to Inc." ,
        1343 to "Synopsys to Inc." ,
        1356 to "Sony Corporation" ,
        1360 to "Fuji Xerox Co. to Ltd." ,
        1367 to "ATEN International Co. Ltd." ,
        1369 to "Cadence Design Systems to Inc." ,
        1386 to "WACOM Co. to Ltd." ,
        1389 to "EIZO Corporation" ,
        1390 to "Elecom Co. to Ltd." ,
        1394 to "Conexant Systems to Inc." ,
        1398 to "BAFO/Quality Computer Accessories" ,
        1403 to "Y-E Data to Inc." ,
        1404 to "AVM GmbH" ,
        1410 to "Roland Corporation" ,
        1412 to "RATOC Systems to Inc." ,
        1419 to "Infineon Technologies" ,
        1423 to "Alcor Micro to Corp." ,
        1424 to "OMRON Corporation" ,
        1447 to "Bose Corporation" ,
        1449 to "OmniVision Technologies to Inc." ,
        1452 to "Apple" ,
        1453 to "Y.C. Cable U.S.A. to Inc" ,
        14627 to "National Instruments" ,
        1470 to "Tyco Electronics Corp. to a TE Connectivity Ltd. company" ,
        1473 to "MegaChips Corporation" ,
        1478 to "Qualcomm to Inc" ,
        1480 to "Foxlink/Cheng Uei Precision Industry Co. to Ltd." ,
        1482 to "Ricoh Company Ltd." ,
        1498 to "Microtek International Inc." ,
        1504 to "Symbol Technologies" ,
        1507 to "Genesys Logic to Inc." ,
        1509 to "Fuji Electric Co. to Ltd." ,
        1525 to "Unixtar Technology Inc." ,
        1529 to "Datalogic ADC" ,
        1535 to "LeCroy Corporation" ,
        1539 to "Novatek Microelectronics Corp." ,
        1545 to "SMK Manufacturing Inc." ,
        1551 to "Joinsoon Electronics Mfg. Co. to Ltd." ,
        1555 to "TransAct Technologies Incorporated" ,
        1561 to "Seiko Instruments Inc." ,
        1582 to "JPC/MAIN SUPER Inc." ,
        1583 to "Sin Sheng Terminal & Machine Inc." ,
        1593 to "Chrontel to Inc." ,
        1611 to "Analog Devices to Inc. Development Tools" ,
        1612 to "Ji-Haw Industrial Co. to Ltd" ,
        1614 to "Suyin Corporation" ,
        1621 to "Space Shuttle Hi-Tech Co.,Ltd." ,
        1622 to "Glory Mark Electronic Ltd." ,
        1623 to "Tekcon Electronics Corp." ,
        1624 to "Sigma Designs to Inc." ,
        1631 to "Good Way Technology Co. to Ltd. & GWC technology Inc" ,
        1632 to "TSAY-E (BVI , International Inc." ,
        1633 to "Hamamatsu Photonics K.K." ,
        1642 to "Total Technologies to Ltd." ,
        1659 to "Prolific Technology to Inc." ,
        16700 to "Dell Inc." ,
        1680 to "Golden Bridge Electech Inc." ,
        1689 to "Tektronix to Inc." ,
        1690 to "Askey Computer Corporation" ,
        1709 to "Greatland Electronics Taiwan Ltd." ,
        1710 to "Eurofins Digital Testing Belgium" ,
        1720 to "Pixela Corporation" ,
        1724 to "Oki Data Corporation" ,
        1727 to "Leoco Corporation" ,
        1732 to "Bizlink Technology to Inc." ,
        1736 to "SIIG to Inc." ,
        1747 to "Mitsubishi Electric Corporation" ,
        1758 to "Heisei Technology Co. to Ltd." ,
        1802 to "Oki Electric Industry Co. to Ltd." ,
        1805 to "Comoss Electronic Co. to Ltd." ,
        1809 to "Magic Control Technology Corp." ,
        1816 to "Imation Corp." ,
        1838 to "Sunix Co. to Ltd." ,
        1846 to "Lorom Industrial Co. to Ltd." ,
        1848 to "Mad Catz to Inc." ,
        1899 to "HID Global GmbH" ,
        1901 to "Denso Corporation" ,
        1913 to "Fairchild Semiconductor" ,
        1921 to "SanDisk Corporation" ,
        1937 to "Copartner Technology Corporation" ,
        1954 to "National Technical Systems" ,
        1971 to "Plustek to Inc." ,
        1972 to "OLYMPUS CORPORATION" ,
        1975 to "TIME Interconnect Ltd." ,
        1994 to "AVerMedia Technologies to Inc." ,
        1999 to "Casio Computer Co. to Ltd." ,
        2015 to "David Electronics Company to Ltd." ,
        2039 to "Century Corporation" ,
        2058 to "Evermuch Technology Co. to Ltd." ,
        2101 to "Action Star Enterprise Co. to Ltd." ,
        2112 to "Argosy Research Inc." ,
        2122 to "Wipro Limited" ,
        2159 to "MEC IMEX INC/HPT" ,
        2205 to "Icron Technologies Corporation" ,
        2247 to "TAI TWUN ENTERPRISE CO. to LTD." ,
        2276 to "Pioneer Corporation" ,
        2278 to "Gemalto SA" ,
        2310 to "FARADAY Technology Corp." ,
        2313 to "Audio-Technica Corp." ,
        2316 to "Silicon Motion to Inc. - Taiwan" ,
        2334 to "Garmin International" ,
        2352 to "Toshiba Corporation" ,
        2362 to "Pixart Imaging to Inc." ,
        2363 to "Plextor LLC" ,
        2366 to "J.S.T. Mfg. Co. to Ltd." ,
        2385 to "Kingston Technology Company" ,
        2389 to "NVIDIA" ,
        2395 to "Medialogic Corporation" ,
        2397 to "Polycom to Inc." ,
        2468 to "Contech Research to Inc." ,
        2472 to "Lin Shiung Enterprise Co. to Ltd." ,
        2475 to "Japan Cash Machine Co. to Ltd." ,
        2498 to "NISCA Corporation" ,
        2511 to "Electronics Testing Center to Taiwan" ,
        2522 to "A-FOUR TECH CO. to LTD." ,
        2555 to "Altera" ,
        2578 to "Cambridge Silicon Radio Ltd." ,
        2583 to "HOYA Corporation" ,
        2631 to "Hirose Electric Co. to Ltd." ,
        2636 to "COMPUTEX Co. to Ltd." ,
        2640 to "Mimaki Engineering Co. to Ltd." ,
        2652 to "Broadcom Corp." ,
        2667 to "Green House Co. to Ltd." ,
        2702 to "Japan Aviation Electronics Industry Ltd. (JAE ," ,
        2727 to "Wincor Nixdorf GmbH & Co KG" ,
        2733 to "Rohde & Schwarz GmbH & Co. KG" ,
        2787 to "Allion Labs to Inc." ,
        2821 to "ASUSTek Computer Inc." ,
        2849 to "Yokogawa Electric Corporation" ,
        2851 to "Pan-Asia Electronics Co. to Ltd." ,
        2894 to "Musical Electronics Ltd." ,
        2907 to "Anritsu Corporation" ,
        2922 to "Maxim Integrated Products" ,
        2965 to "ASIX Electronics Corporation" ,
        2967 to "O2Micro to Inc." ,
        3010 to "Seagate Technology LLC" ,
        3034 to "Realtek Semiconductor Corp." ,
        3035 to "Ericsson AB" ,
        3044 to "Elka International Ltd." ,
        3056 to "Pace Micro Technology PLC" ,
        3108 to "Taiyo Yuden Co. to Ltd." ,
        3129 to "Aeroflex" ,
        3132 to "Radius Co. to Ltd." ,
        3141 to "Sonix Technology Co. to Ltd." ,
        3158 to "Billion Bright (HK , Corporation Limited" ,
        3161 to "Dong Guan Shinko Wire Co. to Ltd." ,
        3170 to "Chant Sincere Co. to Ltd" ,
        3190 to "Solid State System Co. to Ltd." ,
        3209 to "Honda Tsushin Kogyo Co. to Ltd" ,
        3245 to "Motorola Solutions" ,
        3255 to "Singatron Enterprise Co. Ltd." ,
        3268 to "emsys Embedded Systems GmbH" ,
        32902 to "Intel Corporation" ,
        3294 to "Z-Com INC." ,
        3313 to "e-CONN ELECTRONIC CO. to LTD." ,
        3314 to "ENE Technology Inc." ,
        3351 to "NALTEC to Inc." ,
        3402 to "NF Corporation" ,
        3403 to "Grape Systems Inc." ,
        3409 to "Volex (Asia , Pte Ltd" ,
        3425 to "MEILU ELECTRONICS (SHENZHEN , CO. to LTD." ,
        3441 to "Hirakawa Hewtech Corp." ,
        3452 to "Taiwan Line Tek Electronic Co. to Ltd." ,
        3463 to "Dolby Laboratories Inc." ,
        3468 to "C-MEDIA ELECTRONICS INC." ,
        3472 to "Sure-Fire Electrical Corporation" ,
        3495 to "IOGEAR to Inc." ,
        3504 to "Micro-Star International Co. to Ltd." ,
        3537 to "Contek Electronics Co. to Ltd." ,
        3540 to "Custom Engineering SPA" ,
        3641 to "Smart Modular Technologies to Inc." ,
        3658 to "Shenzhen Bao Hing Electric Wire & Cable Mfr. Co." ,
        3673 to "Bourns to Inc." ,
        3690 to "Megawin Technology Co. to Ltd." ,
        3698 to "Hsi-Chin Electronics Co. to Ltd." ,
        3714 to "Ching Tai Electric Wire & Cable Co. to Ltd." ,
        3724 to "Well Force Electronic Co. to Ltd" ,
        3725 to "MediaTek Inc." ,
        3728 to "CRU" ,
        3744 to "Ours Technology Inc." ,
        3762 to "Y-S ELECTRONIC CO. to LTD." ,
        3778 to "Sweetray Industrial Ltd." ,
        3779 to "Axell Corporation" ,
        3782 to "InnoVISION Multimedia Limited" ,
        3790 to "TaiSol Electronics Co. to Ltd." ,
        3812 to "Sunrich Technology (H.K. , Ltd." ,
        3868 to "Funai Electric Co. to Ltd." ,
        3873 to "IOI Technology Corporation" ,
        3890 to "YFC-BonEagle Electric Co. to Ltd." ,
        3896 to "Nien-Yi Industrial Corp." ,
        3916 to "WORLDWIDE CABLE OPTO CORP." ,
        3923 to "Taiyo Cable (Dongguan , Co. Ltd." ,
        3924 to "Kawai Musical Instruments Mfg. Co. to Ltd." ,
        3936 to "GuangZhou Chief Tech Electronic Technology Co. Ltd." ,
        3944 to "UQUEST to LTD." ,
        3991 to "CviLux Corporation" ,
        4003 to "Chief Land Electronic Co. to Ltd." ,
        4046 to "Sony Mobile Communications" ,
        4087 to "CHI SHING COMPUTER ACCESSORIES CO. to LTD." ,
        4096 to "Speed Tech Corp." ,
        4100 to "LG Electronics Inc." ,
        4101 to "Apacer Technology Inc." ,
        4134 to "Newly Corporation" ,
        4168 to "Targus Group International" ,
        4172 to "AMCO TEC International Inc." ,
        4183 to "ON Semiconductor" ,
        4184 to "Western Digital Technologies to Inc." ,
        4227 to "CANON ELECTRONICS INC." ,
        4235 to "Grand-tek Technology Co. to Ltd." ,
        4236 to "Robert Bosch GmbH" ,
        4238 to "Lotes Co. to Ltd." ,
        4266 to "Cables To Go" ,
        4267 to "Universal Global Scientific Industrial Co. to Ltd." ,
        4292 to "Silicon Laboratories to Inc." ,
        4301 to "Kycon Inc." ,
        4362 to "Moxa Inc." ,
        4370 to "Golden Bright (Sichuan , Electronic Technology Co Ltd" ,
        4382 to "VSO ELECTRONICS CO. to LTD." ,
        4398 to "Master Hill Electric Wire and Cable Co. to Ltd." ,
        4477 to "Santa Electronic Inc." ,
        4505 to "Sierra Wireless Inc." ,
        4522 to "GlobalMedia Group to LLC" ,
        4528 to "ATECH FLASH TECHNOLOGY" ,
        4643 to "SKYCABLE ENTERPRISE CO. to LTD." ,
        4703 to "ADATA Technology Co. to Ltd." ,
        4716 to "Aristocrat Technologies" ,
        4717 to "Bel Stewart" ,
        4742 to "MARVELL SEMICONDUCTOR to INC." ,
        4756 to "RISO KAGAKU CORP." ,
        4792 to "Zhejiang Xinya Electronic Technology Co. to Ltd." ,
        4817 to "Huawei Technologies Co. to Ltd." ,
        4823 to "Better Holdings (HK , Limited" ,
        4907 to "Konica Minolta to Inc." ,
        4925 to "Jasco Products Company" ,
        4989 to "Pericom Semiconductor Corp." ,
        5008 to "TomTom International B.V." ,
        5075 to "AzureWave Technologies to Inc." ,
        5117 to "Initio Corporation" ,
        5118 to "Phison Electronics Corp." ,
        5134 to "Telechips to Inc." ,
        5145 to "ABILITY ENTERPRISE CO. to LTD." ,
        5148 to "Leviton Manufacturing" ,
        5271 to "Panstrong Company Ltd." ,
        5293 to "CTK Corporation" ,
        5296 to "StarTech.com Ltd." ,
        5376 to "Ellisys" ,
        5404 to "VeriSilicon Holdings Co. to Ltd." ,
        5421 to "JMicron Technology Corp." ,
        5422 to "HLDS (Hitachi-LG Data Storage to Inc. ," ,
        5440 to "Phihong Technology Co. to Ltd." ,
        5451 to "PNY Technologies Inc." ,
        5453 to "Rapid Conn to Connect County Holdings Bhd" ,
        5454 to "D & M Holdings to Inc." ,
        5480 to "Sunf Pu Technology Co. to Ltd" ,
        5488 to "ALLTOP TECHNOLOGY CO. to LTD." ,
        5510 to "Palconn Technology Co. to Ltd." ,
        5528 to "Kunshan Guoji Electronics Co. to Ltd." ,
        5546 to "DongGuan Ya Lian Electronics Co. to Ltd." ,
        5645 to "Samtec" ,
        5694 to "HongLin Electronics Co. to Ltd." ,
        5753 to "Total Phase" ,
        5766 to "ZOOM Corporation" ,
        5836 to "silex technology to Inc." ,
        5946 to "F. Hoffmann-La Roche AG" ,
        5960 to "MQP Electronics Ltd." ,
        5964 to "ASMedia Technology Inc." ,
        5998 to "UD electronic corp." ,
        6001 to "Shenzhen Alex Connector Co. to Ltd." ,
        6002 to "System Level Solutions to Inc." ,
        6018 to "Spreadtrum Hong Kong Limited" ,
        6024 to "ShenZhen Litkconn Technology Co. to Ltd." ,
        6053 to "Advanced Connection Technology Inc." ,
        6095 to "Hip Hing Cable & Plug Mfy. Ltd." ,
        6121 to "DisplayLink (UK , Ltd." ,
        6127 to "Lenovo" ,
        6133 to "K.K. Rocky" ,
        6160 to "Wanshih Electronic Co. to Ltd." ,
        6185 to "Dongguan YuQiu Electronics Co. to Ltd." ,
        6193 to "Gwo Jinn Industries Co. to Ltd." ,
        6297 to "Linkiss Co. to Ltd." ,
        6353 to "Google Inc." ,
        6394 to "Kuang Ying Computer Equipment Co. to Ltd." ,
        6421 to "Nordic Semiconductor ASA" ,
        6448 to "Shenzhen Xianhe Technology Co. to Ltd." ,
        6449 to "Ningbo Broad Telecommunication Co. to Ltd." ,
        6470 to "Irisguard UK Ltd" ,
        6473 to "Lab126" ,
        6481 to "Hyperstone GmbH" ,
        6487 to "BIOS Corporation" ,
        6626 to "Solomon Systech Limited" ,
        6639 to "Pak Heng Technology (Shenzhen , Co. to Ltd." ,
        6655 to "Best Buy China Ltd." ,
        6666 to "USB-IF non-workshop" ,
        6709 to "Artesyn Technologies Inc." ,
        6720 to "TERMINUS TECHNOLOGY INC." ,
        6766 to "Global Unichip Corp." ,
        6786 to "Proconn Technology Co. to Ltd." ,
        6794 to "Simula Technology Inc." ,
        6795 to "SGS Taiwan Ltd." ,
        6830 to "Johnson Component & Equipments Co. to Ltd." ,
        6834 to "Allied Vision Technologies GmbH" ,
        6859 to "Salcomp Plc" ,
        6865 to "Desan Wire Co. to Ltd." ,
        6944 to "MStar Semiconductor to Inc." ,
        6984 to "Plastron Precision Co. to Ltd." ,
        7013 to "The Hong Kong Standards and Testing Centre Ltd." ,
        7048 to "ShenMing Electron (Dong Guan , Co. to Ltd." ,
        7086 to "Vuzix Corporation" ,
        7108 to "Ford Motor Co." ,
        7118 to "Contac Cable Industrial Limited" ,
        7119 to "Sunplus Innovation Technology Inc." ,
        7120 to "Hangzhou Riyue Electronics Co. to Ltd." ,
        7158 to "Orient Semiconductor Electronics to Ltd." ,
        7207 to "SHENZHEN DNS INDUSTRIES CO. to LTD." ,
        7217 to "LS Mtron Ltd." ,
        7229 to "NONIN MEDICAL INC." ,
        7275 to "Philips & Lite-ON Digital Solutions Corporation" ,
        7310 to "ASTRON INTERNATIONAL CORP." ,
        7320 to "ALPINE ELECTRONICS to INC." ,
        7347 to "Aces Electronics Co. to Ltd." ,
        7348 to "OPEX CORPORATION" ,
        7390 to "Telecommunications Technology Association (TTA ," ,
        7434 to "Visteon Corporation" ,
        7465 to "Horng Tong Enterprise Co. to Ltd." ,
        7501 to "Pegatron Corporation" ,
        7516 to "Fresco Logic Inc." ,
        7529 to "Walta Electronic Co. to Ltd." ,
        7543 to "Yueqing Changling Electronic Instrument Corp. to Ltd." ,
        7584 to "Parade Technologies to Inc." ,
        7647 to "L&T Technology Services" ,
        7649 to "Actions Microelectronics Co. to Ltd." ,
        7666 to "China Telecommunication Technology Labs - Terminals" ,
        7668 to "SHEN ZHEN FORMAN PRECISION INDUSTRY CO. to LTD." ,
        7682 to "GLOBEMASTER TECHNOLOGIES CO. to LTD." ,
        7696 to "Point Grey Research Inc." ,
        7751 to "HUNG TA H.T.ENTERPRISE CO. to LTD." ,
        7758 to "Etron Technology to Inc." ,
        7795 to "COMLINK ELECTRONICS CO. to LTD." ,
        7818 to "HIBEST Electronic (DongGuan , Co. to Ltd." ,
        7825 to "Other World Computing" ,
        7863 to "WIN WIN PRECISION INDUSTRIAL CO. to LTD." ,
        7879 to "Gefen Inc." ,
        7881 to "MOSER BAER INDIA LIMITED" ,
        7898 to "AIRTIES WIRELESS NETWORKS" ,
        7956 to "Astoria Networks GmbH" ,
        7969 to "Scosche Industries" ,
        7976 to "Cal-Comp Electronics & Communications" ,
        7977 to "Analogix Semiconductor to Inc." ,
        7989 to "Amphenol ShouhMin Industry (ShenZhen , Co. to Ltd" ,
        7996 to "Chang Yang Electronics Company Ltd." ,
        8073 to "Dongguan Goldconn Electronics Co. to Ltd." ,
        8074 to "Morning Star Industrial Co. to Ltd." ,
        8117 to "Unify Software and Solutions GmbH & Co. KG" ,
        8137 to "NXP Semiconductors" ,
        8181 to "Changzhou Wujin BEST Electronic Cables Co. to Ltd." ,
        8205 to "Belkin Electronic (Changzhou , Co. to Ltd." ,
        8220 to "Freeport Resources Enterprises Corp." ,
        8222 to "Qingdao Haier Telecom Co. to Ltd." ,
        8284 to "Shenzhen Tronixin Electronics Co. to Ltd." ,
        8294 to "Unicorn Electronics Components Co. to Ltd." ,
        8334 to "Luxshare-ICT" ,
        8341 to "CE LINK LIMITED" ,
        8342 to "Microconn Electronic Co. to Ltd." ,
        8367 to "Shenzhen CARVE Electronics Co. to Ltd." ,
        8382 to "BURY GmbH & Co. KG" ,
        8384 to "FENGHUA KINGSUN CO. to LTD." ,
        8386 to "Sumitomo Electric Ind. to Ltd. to Optical Comm. R&D Lab" ,
        8439 to "XIMEA s.r.o." ,
        8457 to "VIA Labs to Inc." ,
        8492 to "Shenzhen Linoya Electronic Co. to Ltd." ,
        8494 to "Amphenol AssembleTech (Xiamen , Co. to Ltd." ,
        8524 to "Y Soft Corporation" ,
        8550 to "JVC KENWOOD Corporation" ,
        8564 to "Transcend Information to Inc." ,
        8566 to "TMC/Allion Test Labs" ,
        8613 to "Genesis Technology USA to Inc." ,
        8627 to "Dongguan Teconn Electronics Technology Co. to Ltd." ,
        8644 to "Netcom Technology (HK , Limited" ,
        8659 to "Compupack Technology Co. to Ltd." ,
        8667 to "G-Max Technology Co. to Ltd." ,
        8679 to "Sagemcom Broadband SAS" ,
        8695 to "Wuerth-Elektronik eiSos GmbH & Co. KG" ,
        8707 to "Shin Shin Co. to Ltd." ,
        8709 to "3eYamaichi Electronics Co. to Ltd." ,
        8710 to "Wiretek International Investment Ltd." ,
        8711 to "Fuzhou Rockchip Electronics Co. to Ltd." ,
        8752 to "Plugable Technologies" ,
        8756 to "T-CONN PRECISION CORPORATION" ,
        8831 to "Granite River Labs" ,
        8842 to "Hotron Precision Electronic Ind. Corp." ,
        8875 to "Trigence Semiconductor to Inc." ,
        8888 to "Motorola Mobility Inc." ,
        8904 to "Karming Electronic (Shenzhen , Co. to Ltd." ,
        8981 to "Avery Design Systems to Inc." ,
        8993 to "iKingdom Corp. (d.b.a. iConnectivity ," ,
        9051 to "KangXiang Electronic Co. to Ltd." ,
        9068 to "ZheJiang Chunsheng Electronics Co. to Ltd." ,
        9130 to "DOK (HK , Trading Limited" ,
        9132 to "Marunix Electron Limited" ,
        9165 to "Avconn Precise Connector Co. to Ltd." ,
        9184 to "BitifEye Digital Test Solutions GmbH" ,
        9205 to "Speed Conn Co. to Ltd." ,
        9222 to "INSIDE Secure" ,
        9292 to "Minebea Co. to Ltd." ,
        9299 to "BAANTO" ,
        9338 to "Suzhou Jutze Technologies Co. to Ltd" ,
        9355 to "DONGGUAN SYNCONN PRECISION INDUSTRY CO. LTD." ,
        9382 to "Shenzhen Pangngai Industrial Co. to Ltd." ,
        9422 to "Shenzhen Deren Electronic Co. to Ltd." ,
        9424 to "Smith Micro Software to Inc." ,
        9453 to "ZEN FACTORY GROUP (ASIA , LTD." ,
        9481 to "Chain-In Electronic Co. to Ltd." ,
        9514 to "SUZHOU KELI TECHNOLOGY DEVELOPMENT CO. to LTD." ,
        9515 to "TOP Exactitude Industry (ShenZhen , Co. to Ltd." ,
        9525 to "ShenZhen Hogend Precision Technology Co. to Ltd." ,
        9527 to "Norel Systems Ltd." ,
        9556 to "ASSA ABLOY AB" ,
        9575 to "DongGuan LongTao Electronic Co. to Ltd." ,
        9577 to "DongGuan City MingJi Electronics Co. to Ltd." ,
        9589 to "Weida Hi-Tech Co. to Ltd." ,
        9593 to "Dongguan Wisechamp Electronic Co. to Ltd." ,
        9613 to "Sequans Communications" ,
        9636 to "ALGOLTEK to INC." ,
        9651 to "DongGuan Elinke Industrial Co. to Ltd." ,
        9679 to "Corning Optical Communications LLC" ,
        9714 to "Dongguan Jinyue Electronics Co. to Ltd." ,
        9723 to "RICOH IMAGING COMPANY to LTD." ,
        9742 to "DongGuan HYX Industrial Co. to Ltd." ,
        9753 to "Advanced Silicon SA" ,
        9756 to "EISST Limited" ,
        9771 to "YTOP Electronics Technical (Kunshan , Co. to Ltd." ,
        9841 to "Innovative Logic" ,
        9842 to "GoPro" ,
        9846 to "Basler AG" ,
        9851 to "Palpilot International Corp." ,
        9896 to "UNIREX CORPORATION" ,
        9917 to "Integral Memory Plc." ,
        9973 to "Morning Star Digital Connector Co. to Ltd." ,
        9984 to "MITACHI CO. to LTD." ,
        9999 to "HGST to a Western Digital Company" ,
    )
    
    val CLASSES = mapOf (
        254 to "USB_CLASS_APP_SPEC",
        1 to "USB_CLASS_AUDIO",
        10 to "USB_CLASS_CDC_DATA",
        2 to "USB_CLASS_COMM",
        13 to "USB_CLASS_CONTENT_SEC",
        11 to "USB_CLASS_CSCID",
        3 to "USB_CLASS_HID",
        9 to "USB_CLASS_HUB",
        8 to "USB_CLASS_MASS_STORAGE",
        239 to "USB_CLASS_MISC",
        0 to "USB_CLASS_PER_INTERFACE",
        5 to "USB_CLASS_PHYSICA",
        7 to "USB_CLASS_PRINTER",
        6 to "USB_CLASS_STILL_IMAGE",
        255 to "USB_CLASS_VENDOR_SPEC",
        14 to "USB_CLASS_VIDEO",
        224 to "USB_CLASS_WIRELESS_CONTROLLER",
    )

	fun vendorName(vendor_id: Int): String {
        return IDS[vendor_id] ?: ""
    }
}
